// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Syntra.Modules.Management.Infrastructure.Persistence;

#nullable disable

namespace Syntra.Modules.Management.Infrastructure.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    partial class ManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Syntra.Modules.Management.Domain.ApiClients.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ApiClients", "management");
                });

            modelBuilder.Entity("Syntra.Modules.Management.Domain.ApiClients.ApiClient", b =>
                {
                    b.OwnsOne("Syntra.Modules.Management.Domain.ApiClients.ValueObjects.ApiClientCredential", "Credential", b1 =>
                        {
                            b1.Property<Guid>("ApiClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ClientId");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ExpiresAt");

                            b1.Property<string>("SecretHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("SecretHash");

                            b1.HasKey("ApiClientId");

                            b1.HasIndex("ClientId")
                                .IsUnique();

                            b1.ToTable("ApiClients", "management");

                            b1.WithOwner()
                                .HasForeignKey("ApiClientId");
                        });

                    b.OwnsOne("Syntra.Modules.Management.Domain.ApiClients.ValueObjects.ApiClientDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("ApiClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("ApiClientId");

                            b1.ToTable("ApiClients", "management");

                            b1.WithOwner()
                                .HasForeignKey("ApiClientId");
                        });

                    b.OwnsOne("Syntra.Modules.Management.Domain.ApiClients.ValueObjects.ApiClientName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ApiClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Name");

                            b1.HasKey("ApiClientId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ApiClients", "management");

                            b1.WithOwner()
                                .HasForeignKey("ApiClientId");
                        });

                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
