<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ApiSessions\GetByClientId\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Syntra.BuildingBlocks\Syntra.BuildingBlocks.Application\Syntra.BuildingBlocks.Application\Syntra.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\Syntra.SharedKernel\Syntra.SharedKernel.csproj" />
    <ProjectReference Include="..\Syntra.Modules.Authentication.Domain\Syntra.Modules.Authentication.Domain.csproj" />
  </ItemGroup>

</Project>
